[package]
name = "examit"
version = "0.1.0"
entrypoint = "lib.typ"
authors = ["Steven Williams"]
license = "MIT"
description = "An exam template based on the MIT LaTeX exam.cls"
homepage = "https://github.com/onomou/examit"
keywords = ["exam","test","grading"]
categories = ["components","layout","report"]
disciplines = ["education"]
